[package]
name = "evaluator_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["parser", "ast", "evaluator"]

[dependencies]
parser = {path = "./parser"}
ast = {path = "./ast"}
evaluator = {path = "./evaluator"}

